Fix handling of coercing bare SkyCoord to a list
sunpy/ndcube pull request #400
Opened 2021-02-10 22:31 UTC by rosteen

### Description

Fixes #375 by ensuring that if `axes_coords` is a bare SkyCoord (or other coordinate) rather than a list or tuple, it's put into a single-element list instead of creating a list of smaller SkyCoords.

2021-02-10 22:31 UTC, pep8speaks commented
Hello @rosteen! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`ndcube/ndcube.py`](https://github.com/sunpy/ndcube/blob/498c03235ee47198f457aa0dac3cac3fc2f367eb/ndcube/ndcube.py):

> [Line 330:43](https://github.com/sunpy/ndcube/blob/498c03235ee47198f457aa0dac3cac3fc2f367eb/ndcube/ndcube.py#L330): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','

2021-02-10 22:44 UTC, rosteen commented
Note that while this fixes the specific error reported in #375, I'm not familiar with helioprojective coordinates and thus don't know if the values that come out of that example code now actually make sense. Someone should definitely run that again and confirm that the results are correct. The result is:

```
>>> import sunpy.data.sample
>>> import sunpy.map
>>> from ndcube import NDCube

>>> aia_map = sunpy.map.Map(sunpy.data.sample.AIA_171_IMAGE)
>>> cube = NDCube(data=aia_map.data, wcs=aia_map.wcs)
>>> cube.axis_world_coords()

(<SkyCoord (Helioprojective: obstime=2011-06-07T06:33:02.770, rsun=696000000.0 m, observer=<HeliographicStonyhurst Coordinate (obstime=2011-06-07T06:33:02.770): (lon, lat, radius) in (deg, deg, m)
     (-0.00406308, 0.04787238, 1.51846026e+11)>): (Tx, Ty) in arcsec
     [[(-1228.76466158, -1224.62447509), (-1226.36196228, -1224.63038192),
       (-1223.95926264, -1224.63628858), ...,
       ( 1224.44975018, -1230.56881707), ( 1226.85245064, -1230.57455382),
       ( 1229.25515076, -1230.58029041)],
      [(-1228.75883987, -1222.22181793), (-1226.35614057, -1222.22772459),
       (-1223.95344093, -1222.23363109), ...,
       ( 1224.45557209, -1228.16615958), ( 1226.85827254, -1228.1718965 ),
       ( 1229.26097267, -1228.17763325)],
      [(-1228.75301816, -1219.81916044), (-1226.35031885, -1219.82506693),
       (-1223.94761922, -1219.83097326), ...,
       ( 1224.46139399, -1225.76350175), ( 1226.86409445, -1225.76923884),
       ( 1229.26679457, -1225.77497576)],
      ...,
      [(-1222.82069357,  1228.5464895 ), (-1220.41799325,  1228.54075277),
       (-1218.0152926 ,  1228.53501588), ...,
       ( 1230.39391586,  1222.60248691), ( 1232.79661569,  1222.59658039),
       ( 1235.19931518,  1222.59067371)],
      [(-1222.81487186,  1230.94914699), (-1220.41217154,  1230.94341043),
       (-1218.00947089,  1230.93767371), ...,
       ( 1230.39973777,  1225.00514474), ( 1232.80243759,  1224.99923805),
       ( 1235.20513709,  1224.9933312 )],
      [(-1222.80905014,  1233.35180416), (-1220.40634982,  1233.34606776),
       (-1218.00364917,  1233.3403312 ), ...,
       ( 1230.40555967,  1227.40780223), ( 1232.8082595 ,  1227.40189538),
       ( 1235.21095899,  1227.39598836)]]>,)
```

2021-02-11 09:16 UTC, DanRyanIrish requested changes
Thanks for this PR @rosteen!  Made a couple suggestions during code review.

In addition, the codestyle test says there's [trailing whitespace somewhere](https://dev.azure.com/sunpy/ndcube/_build/results?buildId=13922&view=logs&jobId=19e9af05-3245-5acd-5c3d-d573c2eeba16&j=19e9af05-3245-5acd-5c3d-d573c2eeba16&t=61fe8148-ee95-5507-e242-e6709c8b04c8) that should be removed.  If you have tox installed, you should be able to do
`tox -e codestyle`
from the top level directory of the ndcube repo and then commit the changes it makes.

Also, could you add a test to check [L330](https://github.com/sunpy/ndcube/pull/400/files#diff-929794bb532be1486907b360285433b432f8505ab7e7ff63eca3eab657f7d00dR330)?  I think the easiest way to do this is to to add a new test, e.g.
```python
def test_axes_world_coords_sky_only(ndcube_2d_ln_lt):
```
using the `ndcube_2d_ln_lt` fixture.  See [this test](https://github.com/sunpy/ndcube/blob/master/ndcube/tests/test_ndcube.py#L284) as an example to modify.  Note this test uses the `ndcube_3d_ln_lt_l` fixture where I believe you want to use the `ndcube_2d_ln_lt` fixture.  You shouldn't have to import anything new

2021-02-11 09:16 UTC, DanRyanIrish commented on ndcube/ndcube.py
> +        if type(axes_coords) != list:
```suggestion
        if not isinstance(axes_coords, list):
```

2021-02-11 09:16 UTC, DanRyanIrish commented on ndcube/ndcube.py
> +            if type(axes_coords) == tuple:
```suggestion
            if isinstance(axes_coords, tuple):
```

2021-02-11 15:06 UTC, DanRyanIrish approved these changes

2021-02-11 15:06 UTC, merged

2021-02-11 15:06 UTC, DanRyanIrish commented
Another merged PR!  Thanks so much @rosteen