Joss paper
sunpy/ndcube pull request #599
Opened 2023-03-08 09:25 UTC by DanRyanIrish

## PR Description

This PR writes a paper for submission to the Journal of Open Source Software.

2023-03-08 10:32 UTC, Cadair approved these changes

2023-03-08 13:07 UTC, DanRyanIrish commented
@Cadair @yashrsharma44 @abit2 @adwaitbhope @nabobalis @hayesla @wtbarnes @BaptistePellorceAstro @rosteen @dhomeier @jmbhughes @ayshih @mwest007

Here is the latest draft of the ndcube JOSS paper which I will submit to be associated with our submission to ApJ.  It justifies why ndcube is needed, summaries the package including its main data classes, and mentions ndcube's broader use.  It is largely a summary of certain parts of the ApJ paper in much less detail.  Please feel free to provide any feedback.

Since we've already submitted the ApJ paper, and since JOSS reviews focus a lot on the code-base, I plan to submit this tomorrow.  If you would like more time to provide feedback, please let me know.

Many thanks!

2023-03-08 15:00 UTC, dhomeier requested changes
Thanks, left a few spelling corrections etc. and suggestions on presentation, but I did not go very deep into the technical details.

2023-03-08 15:30 UTC, DanRyanIrish commented on joss_paper/paper.md
> +axes to the physical types they represent.
Good point.  I've just made a minor tweak to your suggestion here.

```suggestion
WCS’s ability to handle many different physical types of coordinates (e.g. spatial,
temporal, spectral, etc.) and their projections onto a data array (e.g. right ascension
and declination, helioprojective latitude and longitude, etc.) make it a succinct,
standardized and powerful way to relate array axes to the physical types they represent.
```

2023-03-08 15:32 UTC, DanRyanIrish commented on joss_paper/paper.md
> +and a Doppler may derived from one of its spectral lines.
```suggestion
One application of this is linking derived data products, e.g. a spectral image cube
and a Doppler map derived from one of its spectral lines.
```

2023-03-08 15:33 UTC, DanRyanIrish commented
> Thanks, left a few spelling corrections etc. and suggestions on presentation, but I did not go very deep into the technical details.

Thanks @dhomeier!

2023-03-08 15:49 UTC, DanRyanIrish commented on joss_paper/paper.bib
> +
```suggestion

@software{jdaviz,
  author       = {JDADF Developers and
                  Averbukh, Jesse and
                  Bradley, Larry and
                  Buikhuizen, Mario and
                  Busko, Ivo and
                  Cherinka, Brian and
                  Conroy, Kyle and
                  Earl, Nicholas and
                  Fox, Ori and
                  Geda, Robel and
                  Jones, Craig and
                  Karatay, Hatice and
                  Kotler, Jenn and
                  Lim, Pey Lian and
                  Morris, Brett and
                  Nguyen, Duy and
                  O'Steen, Richard and
                  Ogaz, Sara and
                  Ogle, Patrick and
                  Otor, O. Justin and
                  Pacifici, Camilla and
                  Robitaille, Thomas and
                  Tollerud, Erik and
                  Volfman, Sabrina},
  title        = {Jdaviz},
  month        = feb,
  year         = 2023,
  note         = {If you use this software, please cite it as below.},
  publisher    = {Zenodo},
  version      = {3.3.0},
  doi          = {10.5281/zenodo.7625637},
  url          = {https://doi.org/10.5281/zenodo.7625637}
}

```

2023-03-08 15:49 UTC, DanRyanIrish commented on joss_paper/paper.md
> +It is also used in the data pipeline of the PUNCH mission [Polarimeter to UNify
```suggestion
Daniel K. Inouye Solar Telescope (DKIST) via the
specutils [@specutils-docs; @specutils-code], jdaviz [@jdaviz], sunraster [@sunraster],
irispy-lmsal [@irispy-docs; @irispy-code], EISPAC [@eispac-docs; @eispac-code] and
DKIST user tools packages which all depend on ndcube.
ndcube is also used in the data pipeline of the PUNCH mission [Polarimeter to UNify
```

2023-03-08 15:49 UTC, DanRyanIrish commented on joss_paper/paper.md
> +Individual researchers are also using the ndcube package in their own analysis
```suggestion
In addition, individual researchers are using the ndcube package in their own analysis
```

2023-03-09 05:32 UTC, nabobalis approved these changes
LGTM

2023-03-09 05:33 UTC, nabobalis commented
Would be nice if it was possible to see the rendered version before submission.

2023-03-09 11:15 UTC, Cadair commented
> Would be nice if it was possible to see the rendered version before submission

When you open the PR to JOSS you get the rendered version while they sort out reviewers etc, it's a very laid back process.

2023-03-09 11:36 UTC, DanRyanIrish commented
> Would be nice if it was possible to see the rendered version before submission.

Available as a zip file here: https://github.com/DanRyanIrish/ndcube/suites/11451658813/artifacts/590718269

2023-03-09 12:19 UTC, merged

2023-03-09 12:33 UTC, DanRyanIrish commented
I have just submitted this to JOSS.  Thanks for all the input!