Convert WCS wrappers to FITS WCS.
sunpy/ndcube pull request #649
Opened 2023-10-28 12:36 UTC by DanRyanIrish

## PR Description

This PR is a draft of a feature to convert a chain of WCS wrapper classes to a FITS-WCS, provided the base-level WCS is a FITS-WCS and only supported wrapper types are involved.  See Issue #648

2023-10-28 12:36 UTC, pep8speaks commented
Hello @DanRyanIrish! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`ndcube/wcs/wcs_tools.py`](https://github.com/sunpy/ndcube/blob/8f48bbcdb923ab4f9b234afcc69132dae1c39cf8/ndcube/wcs/wcs_tools.py):

> [Line 22:80](https://github.com/sunpy/ndcube/blob/8f48bbcdb923ab4f9b234afcc69132dae1c39cf8/ndcube/wcs/wcs_tools.py#L22): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (88 > 79 characters)
> [Line 39:80](https://github.com/sunpy/ndcube/blob/8f48bbcdb923ab4f9b234afcc69132dae1c39cf8/ndcube/wcs/wcs_tools.py#L39): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (97 > 79 characters)
> [Line 43:80](https://github.com/sunpy/ndcube/blob/8f48bbcdb923ab4f9b234afcc69132dae1c39cf8/ndcube/wcs/wcs_tools.py#L43): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (99 > 79 characters)
> [Line 47:80](https://github.com/sunpy/ndcube/blob/8f48bbcdb923ab4f9b234afcc69132dae1c39cf8/ndcube/wcs/wcs_tools.py#L47): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (99 > 79 characters)
> [Line 48:6](https://github.com/sunpy/ndcube/blob/8f48bbcdb923ab4f9b234afcc69132dae1c39cf8/ndcube/wcs/wcs_tools.py#L48): [E901](https://duckduckgo.com/?q=pep8%20E901) IndentationError: unindent does not match any outer indentation level

2023-10-28 12:37 UTC, DanRyanIrish commented
@Cadair @jmason86 Thoughts on this approach?

2023-10-28 19:32 UTC, Cadair commented on ndcube/wcs/wcs_tools.py
> +def slice_fitswcs(fitswcs, slice_items):
You might find the `slice` and `sub` methods on `WCS` useful: https://docs.astropy.org/en/stable/api/astropy.wcs.WCS.html#astropy.wcs.WCS.slice

2023-10-28 19:34 UTC, Cadair commented on ndcube/wcs/wcs_tools.py
> +    while hasattr(low_level_wrapper, "_wcs"):
Well this is horrifying. I think checking if it's an instance of https://docs.astropy.org/en/stable/api/astropy.wcs.wcsapi.BaseWCSWrapper.html#astropy.wcs.wcsapi.BaseWCSWrapper would be slightly better.

2023-10-29 12:52 UTC, DanRyanIrish commented
Thanks @Cadair.  Here's a 2nd draft.  Sticking with the approach for now of not dropping any axes from WCS but letting users know where length-1 dummy axes are needed in the data array for it to be made consistent with the FITS WCS.  It saves a lot of logic or error catching about whether `WCS.sub` can be used.  And in cases where one dependent axis is dropped, but not another, this information will be needed anyway.

Thoughts on this draft/approach, @Cadair @jmason86?

2023-10-30 19:34 UTC, jmason86 commented
I took a look (the test in particular was helpful... thanks for writing it so closely to my use case!) and I think this would do the trick!

2023-10-30 22:24 UTC, DanRyanIrish commented
pre-commit.ci autofix

2023-10-30 22:40 UTC, DanRyanIrish commented
@jmason86 I've released this PR from draft form.  So it would be great to get an official review/approval from you.

@Cadair, would you like to review this also now that it's an official proposed PR?

2023-11-01 18:45 UTC, jmason86 approved these changes
Tested out the code and it indeed appears to operate just as promised!

2023-11-02 16:20 UTC, DanRyanIrish commented
Thanks @jmason86.  Can you take a quick look at [this line](https://github.com/sunpy/ndcube/pull/649/files#diff-5b7d9cc31af80b8b632252bdb6ad5a5d355c1a50d401d8f96df0bb6bd32d2d4fR159) and confirm I have my WCS algebra right?  It gives the right answer in the case I've tested.  But I have a nagging doubt that it might be a specific solution, rather than a truly general one.

2023-11-13 08:22 UTC, DanRyanIrish commented
@Cadair would you still like to give a review on this? Or can we merge it to get it to @jmason86 ?

2023-11-13 14:59 UTC, Cadair approved these changes
Looks good to me, does this need documenting somewhere? Is this even being picked up by our API docs?

2023-11-13 14:59 UTC, Cadair commented on ndcube/wcs/wcs_tools.py
> +    """Create FITS-WCS equivalent to (nested) WCS wrapper object.
```suggestion
    """
    Create FITS-WCS equivalent to (nested) WCS wrapper object.
```

2023-11-13 14:59 UTC, Cadair commented on ndcube/wcs/wcs_tools.py
> +    """Resample the plate scale of a FITS-WCS by a given factor.
```suggestion
    """
    Resample the plate scale of a FITS-WCS by a given factor.
```

2023-11-14 16:07 UTC, DanRyanIrish commented
> Is this even being picked up by our API docs?

I don't know.  The doc test is failing for some reason.  @nabobalis do know why that is?  Looks like something is aiohttp is deprecated...

2023-11-14 17:31 UTC, nabobalis commented
pre-commit.ci autofix

2023-11-14 17:32 UTC, nabobalis commented
Might pass now?

2023-11-14 18:16 UTC, nabobalis commented
Or not: `<unknown>:20: WARNING: py:obj reference target not found: ndcube.wcs.wcs_tools.unwrap_wcs_to_fitswcs`

2023-11-14 18:17 UTC, nabobalis commented on changelog/649.feature.rst
> +Provide new function, `~ndcube.wcs.wcs_tools.unwrap_wcs_to_fitswcs`, to create a `astropy.wcs.WCS` instance equivalent to a sliced and/or resampled WCS instance. Only valid if the underlying implemen
```suggestion
Provides `~ndcube.wcs.tools.unwrap_wcs_to_fitswcs`, a function to create a `astropy.wcs.WCS` instance equivalent to a sliced and/or resampled WCS instance.
Only valid if the underlying implementation of the wrapped WCS instance is also an `astropy.wcs.WCS` instance.
```

2023-11-14 18:17 UTC, nabobalis commented on ndcube/wcs/tools.py
> +        The WCS Wrapper object. Base level WCS implementation must be FITS-WCS.
```suggestion
        The WCS Wrapper object.
        Base level WCS implementation must be FITS-WCS.
```

2023-11-14 18:19 UTC, nabobalis requested changes
Needs a new API page entry. I don't see how it would be pulled in by modapi.

2023-11-14 18:21 UTC, nabobalis commented on ndcube/wcs/tests/test_wcs_tools.py
> +import numpy as np
File needs renaming.

2023-11-15 22:04 UTC, nabobalis approved these changes

2023-11-15 22:04 UTC, nabobalis commented
Hopefully the CI is passing.

2023-11-15 22:13 UTC, merged